name: 'build and publish'
description: 'Builds and Publish the docker image'
inputs:
  docker_build_args:  # id of input
    description: 'Docker build arguments'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Build and publish
      run: |
        ./.scripts/.build.sh "${DH_REPO}" "${IMAGE_NAME}" "${{ inputs.docker_build_args}}" "${ECR_REPO}";
        ./${IMAGE_NAME}/.publish.sh "${DH_REPO}:${IMAGE_NAME}";
        ./${IMAGE_NAME}/.publish.sh "${ECR_REPO}:${IMAGE_NAME}";
      shell: bash
