name: 'build and publish firce'
description: 'Builds and Publish the docker image with force push'
inputs:
  docker_build_args:  # id of input
    description: 'Docker build arguments'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Build and publish force
      run: |
        ./.scripts/.build.sh "${DH_REPO}" "${IMAGE_NAME}" "${{ inputs.docker_build_args}}" "${ECR_REPO}";
        ./${IMAGE_NAME}/.publish.sh "${DH_REPO}:${IMAGE_NAME}" --force;
        ./${IMAGE_NAME}/.publish.sh "${ECR_REPO}:${IMAGE_NAME}" --force;
      shell: bash