name: build and publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  ECR_REPO: public.ecr.aws/l5k6t5t7/cicd-images
  DH_REPO: govtechsg/cicd-images
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: docker run --rm -i hadolint/hadolint < ./ansible/Dockerfile
  alpine:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: alpine
    name: alpine
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq curl
      - name: Download and install awscli v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: Dockerhub login
        run: docker login -u ${{ secrets.DH_USERNAME }} -p ${{ secrets.DH_PASSWORD }};
      - name: ECR public login
        run: /usr/local/bin/aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - name: Build and Publish
        uses: govtechsg/cicd-images/.github/actions/build-and-publish@master

  ansible:
    env:
      IMAGE_NAME: ansible
    runs-on: ubuntu-latest
    name: ansible
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq curl
      - name: Download and install awscli v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: Dockerhub login
        run: docker login -u ${{ secrets.DH_USERNAME }} -p ${{ secrets.DH_PASSWORD }};
      - name: ECR public login
        run: /usr/local/bin/aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - name: Build and Publish
        uses: govtechsg/cicd-images/.github/actions/build-and-publish@master